#!/bin/sh

BITS=384
if test -n "$2"; then BITS=$2; fi

openssl genrsa -out $1 $BITS 2>/dev/null
openssl rsa -in $1 -out /tmp/dknewkey.$$ -pubout -outform PEM 2>/dev/null
if test -f /usr/local/bin/tinydns-data; then
  printf "'%s._domainkey.example.com:k=rsa; p=%s\n" `basename $1` `grep -v ^-- /tmp/dknewkey.$$ | tr -d '\n'`
else
  printf "%s._domainkey\tIN\tTXT\t\"k=rsa; p=%s\"\n" `basename $1` `grep -v ^-- /tmp/dknewkey.$$ | tr -d '\n'`
fi
rm -f /tmp/dknewkey.$$
